services:
  dev_db:
    image: postgres:17.2
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - dev_data:/var/lib/postgresql/data

  test_db:
    image: postgres:17.2
    restart: always
    env_file:
      - .env.test
    ports:
      - 5433:5432
    volumes:
      - test_data:/var/lib/postgresql/data

volumes:
  dev_data:
  test_data:
