services:
  frontend:
    image: frontend
    build:
      context: ../frontend
    container_name: frontend

  db:
    image: postgres:17.2
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    image: backend
    build:
      context: ../backend
    container_name: backend
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:1.27.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
